// Copyright(c) The Maintainers of Nanvix.
// Licensed under the MIT License.

//! Hello-world Wasmtime on Nanvix.
//!
//! Loads a precompiled WASM module (Pulley32 bytecode, generated by
//! the `precompile-wasm` host tool) and runs a trivial `hello()` function
//! that returns 42.
//!
//! Console output uses the kernel debug syscall (NR_DEBUG=0) since
//! stdout via write() is not yet functional in standalone mode.

extern crate alloc;

/// Precompiled Pulley32 bytecode (generated by precompile-wasm on the host).
static PRECOMPILED: &[u8] = include_bytes!("../hello.cwasm");

/// Write to the kernel debug console via syscall NR_DEBUG=0.
fn debug_print(msg: &str) {
    for chunk in msg.as_bytes().chunks(200) {
        unsafe {
            core::arch::asm!(
                "int 0x80",
                inout("eax") 0u32 => _,
                in("ebx") chunk.as_ptr(),
                in("ecx") chunk.len(),
                lateout("edx") _,
                options(nostack, preserves_flags)
            );
        }
    }
}

fn run() -> Result<i32, wasmtime::Error> {
    let mut config = wasmtime::Config::new();
    config.target("pulley32")?;
    // 32-bit safe memory settings (must match precompile-wasm Config).
    config.memory_reservation(1 << 20);
    config.memory_guard_size(4096);
    config.memory_reservation_for_growth(65536);
    config.guard_before_linear_memory(false);
    let engine = wasmtime::Engine::new(&config)?;

    debug_print("[wasmtime] Deserializing module...\n");
    let module = unsafe { wasmtime::Module::deserialize(&engine, PRECOMPILED)? };

    debug_print("[wasmtime] Instantiating...\n");
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[])?;

    debug_print("[wasmtime] Calling hello()...\n");
    let hello = instance.get_typed_func::<(), i32>(&mut store, "hello")?;
    let result = hello.call(&mut store, ())?;

    // Explicit cleanup before returning (avoids potential drop-order issues).
    drop(store);
    drop(module);
    drop(engine);

    Ok(result)
}

fn main() {
    debug_print("Hello from Wasmtime on Nanvix!\n");

    match run() {
        Ok(result) => {
            let msg = alloc::format!("hello() = {}\n", result);
            debug_print(&msg);
        }
        Err(e) => {
            debug_print("[wasmtime] ERROR: ");
            let msg = alloc::format!("{}\n", e);
            debug_print(&msg);
        }
    }
    // main() returns → nvx runtime → pm::exit(0) → kernel shutdown → nanvixd exit
}
